// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { MediaReadMediaData, MediaReadMediaResponse, MediaReadUserData, MediaReadUserResponse, MediaSearchMediaData, MediaSearchMediaResponse, UtilsHealthCheckResponse } from './types.gen';

export class MediaService {
    /**
     * Read Media
     * Retrieve media.
     * @param data The data for the request.
     * @param data.mediaId
     * @param data.xAnilistToken
     * @returns app__media__graphql_media_schema__Media Successful Response
     * @throws ApiError
     */
    public static readMedia(data: MediaReadMediaData): CancelablePromise<MediaReadMediaResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/media/{media_id}',
            path: {
                media_id: data.mediaId
            },
            headers: {
                'X-Anilist-Token': data.xAnilistToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User
     * Retrieve user's media list.
     * @param data The data for the request.
     * @param data.userName
     * @param data.xAnilistToken
     * @returns MediaListCollection Successful Response
     * @throws ApiError
     */
    public static readUser(data: MediaReadUserData): CancelablePromise<MediaReadUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/user/{user_name}',
            path: {
                user_name: data.userName
            },
            headers: {
                'X-Anilist-Token': data.xAnilistToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Search Media
     * Search for media by title.
     * media_type can be 'ANIME' or 'MANGA'.
     * @param data The data for the request.
     * @param data.searchQuery
     * @param data.mediaType
     * @param data.xAnilistToken
     * @returns SearchPage Successful Response
     * @throws ApiError
     */
    public static searchMedia(data: MediaSearchMediaData): CancelablePromise<MediaSearchMediaResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/search/{search_query}',
            path: {
                search_query: data.searchQuery
            },
            headers: {
                'X-Anilist-Token': data.xAnilistToken
            },
            query: {
                media_type: data.mediaType
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SearchService {
    /**
     * Search Media
     * Search for media by title.
     * media_type can be 'ANIME' or 'MANGA'.
     * @param data The data for the request.
     * @param data.searchQuery
     * @param data.mediaType
     * @param data.xAnilistToken
     * @returns SearchPage Successful Response
     * @throws ApiError
     */
    public static mediaSearchMedia(data: MediaSearchMediaData): CancelablePromise<MediaSearchMediaResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/search/{search_query}',
            path: {
                search_query: data.searchQuery
            },
            headers: {
                'X-Anilist-Token': data.xAnilistToken
            },
            query: {
                media_type: data.mediaType
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UserService {
    /**
     * Read User
     * Retrieve user's media list.
     * @param data The data for the request.
     * @param data.userName
     * @param data.xAnilistToken
     * @returns MediaListCollection Successful Response
     * @throws ApiError
     */
    public static mediaReadUser(data: MediaReadUserData): CancelablePromise<MediaReadUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/user/{user_name}',
            path: {
                user_name: data.userName
            },
            headers: {
                'X-Anilist-Token': data.xAnilistToken
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}