// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    itemId: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    itemId: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    itemId: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

// Media types (matching backend Pydantic schemas)

export type MediaListStatus = 'COMPLETED' | 'CURRENT' | 'DROPPED' | 'PAUSED' | 'PLANNING' | 'REPEATING';

export type MediaList = {
    mediaId: number;
};

export type MediaListGroup = {
    entries?: Array<(MediaList | null)> | null;
    status?: MediaListStatus | null;
};

export type MediaListCollection = {
    lists?: Array<(MediaListGroup | null)> | null;
};

export type FuzzyDate = {
    day?: number | null;
    month?: number | null;
    year?: number | null;
};

export type MediaTitle = {
    english?: string | null;
    native?: string | null;
    romaji?: string | null;
};

export type MediaCoverImage = {
    color?: string | null;
    extraLarge?: string | null;
    large?: string | null;
    medium?: string | null;
};

export type MediaExternalLink = {
    id: number;
    url?: string | null;
    site: string;
    type?: string | null;
};

export type MediaTag = {
    id: number;
    name: string;
    rank?: number | null;
    category?: string | null;
    description?: string | null;
    isAdult?: boolean | null;
    isGeneralSpoiler?: boolean | null;
    isMediaSpoiler?: boolean | null;
};

export type MediaTrailer = {
    id?: string | null;
    site?: string | null;
    thumbnail?: string | null;
};

export type Studio = {
    id: number;
    name: string;
    isAnimationStudio: boolean;
};

export type StudioConnection = {
    nodes?: Array<(Studio | null)> | null;
};

export type Recommendation = {
    id: number;
    mediaRecommendation?: app__media__graphql_media_schema__Media | null;
    rating?: number | null;
};

export type RecommendationConnection = {
    nodes?: Array<(Recommendation | null)> | null;
};

export type app__media__graphql_media_schema__Media = {
    id: number;
    title?: MediaTitle | null;
    averageScore?: number | null;
    bannerImage?: string | null;
    chapters?: number | null;
    coverImage?: MediaCoverImage | null;
    description?: string | null;
    duration?: number | null;
    endDate?: FuzzyDate | null;
    episodes?: number | null;
    externalLinks?: Array<(MediaExternalLink | null)> | null;
    favourites?: number | null;
    format?: string | null;
    genres?: Array<(string | null)> | null;
    idMal?: number | null;
    isAdult?: boolean | null;
    isLicensed?: boolean | null;
    meanScore?: number | null;
    popularity?: number | null;
    rankings?: Array<unknown> | null;
    recommendations?: RecommendationConnection | null;
    season?: string | null;
    seasonYear?: number | null;
    siteUrl?: string | null;
    source?: string | null;
    startDate?: FuzzyDate | null;
    status?: string | null;
    studios?: StudioConnection | null;
    synonyms?: Array<(string | null)> | null;
    tags?: Array<(MediaTag | null)> | null;
    trailer?: MediaTrailer | null;
    type?: string | null;
    countryOfOrigin?: string | null;
    volumes?: number | null;
};

export type SearchMediaItem = {
    id: number;
    title?: MediaTitle | null;
    coverImage?: { medium?: string | null; large?: string | null } | null;
    type?: string | null;
    format?: string | null;
    status?: string | null;
    averageScore?: number | null;
    startDate?: FuzzyDate | null;
};

export type SearchPage = {
    pageInfo?: {
        total?: number | null;
        currentPage?: number | null;
        lastPage?: number | null;
        hasNextPage?: boolean | null;
        perPage?: number | null;
    } | null;
    media?: Array<(SearchMediaItem | null)> | null;
};

export type MediaReadMediaData = {
    mediaId: number;
};

export type MediaReadMediaResponse = (app__media__graphql_media_schema__Media);

export type MediaReadUserData = {
    userName: string;
};

export type MediaReadUserResponse = (MediaListCollection);

export type MediaSearchMediaData = {
    searchQuery: string;
    mediaType: string;
};

export type MediaSearchMediaResponse = (SearchPage);