// This file is auto-generated by @hey-api/openapi-ts

/**
 * Score & Watcher stats for airing anime by episode and mid-week
 */
export type AiringProgression = {
    /**
     * The episode the stats were recorded at. .5 is the mid point between 2 episodes airing dates.
     */
    episode?: (number | null);
    /**
     * The average score for the media
     */
    score?: (number | null);
    /**
     * The amount of users watching the anime
     */
    watching?: (number | null);
    __typename?: ("AiringProgression" | null);
};

/**
 * Media Airing Schedule. NOTE: We only aim to guarantee that FUTURE airing data is present and accurate.
 */
export type AiringSchedule = {
    /**
     * The time the episode airs at
     */
    airingAt: number;
    /**
     * The airing episode number
     */
    episode: number;
    /**
     * The id of the airing schedule item
     */
    id: number;
    /**
     * The associate media of the airing episode
     */
    media?: (app__media__graphql_media_schema__Media | null);
    /**
     * The associate media id of the airing episode
     */
    mediaId: number;
    /**
     * Seconds until episode starts airing
     */
    timeUntilAiring: number;
    __typename?: ("AiringSchedule" | null);
};

export type AiringScheduleConnection = {
    edges?: (Array<(AiringScheduleEdge | null)> | null);
    nodes?: (Array<(AiringSchedule | null)> | null);
    /**
     * The pagination information
     */
    pageInfo?: (PageInfo | null);
    __typename?: ("AiringScheduleConnection" | null);
};

/**
 * AiringSchedule connection edge
 */
export type AiringScheduleEdge = {
    /**
     * The id of the connection
     */
    id?: (number | null);
    node?: (AiringSchedule | null);
    __typename?: ("AiringScheduleEdge" | null);
};

/**
 * Anime or Manga
 */
export type app__media__graphql_media_schema__Media = {
    /**
     * The media's entire airing schedule
     */
    airingSchedule?: (AiringScheduleConnection | null);
    /**
     * If the media should have forum thread automatically created for it on airing episode release
     */
    autoCreateForumThread?: (boolean | null);
    /**
     * A weighted average score of all the user's scores of the media
     */
    averageScore?: (number | null);
    /**
     * The banner image of the media
     */
    bannerImage?: (string | null);
    /**
     * The amount of chapters the manga has when complete
     */
    chapters?: (number | null);
    /**
     * The characters in the media
     */
    characters?: (CharacterConnection | null);
    /**
     * Where the media was created. (ISO 3166-1 alpha-2)
     */
    countryOfOrigin?: (string | null);
    /**
     * The cover images of the media
     */
    coverImage?: (app__media__graphql_media_schema__MediaCoverImage | null);
    /**
     * Short description of the media's story and characters
     */
    description?: (string | null);
    /**
     * The general length of each anime episode in minutes
     */
    duration?: (number | null);
    /**
     * The last official release date of the media
     */
    endDate?: (FuzzyDate | null);
    /**
     * The amount of episodes the anime has when complete
     */
    episodes?: (number | null);
    /**
     * External links to another site related to the media
     */
    externalLinks?: (Array<(MediaExternalLink | null)> | null);
    /**
     * The amount of user's who have favourited the media
     */
    favourites?: (number | null);
    /**
     * The format the media was released in
     */
    format?: (MediaFormat | null);
    /**
     * The genres of the media
     */
    genres?: (Array<(string | null)> | null);
    /**
     * Official Twitter hashtags for the media
     */
    hashtag?: (string | null);
    /**
     * The id of the media
     */
    id: number;
    /**
     * The mal id of the media
     */
    idMal?: (number | null);
    /**
     * If the media is intended only for 18+ adult audiences
     */
    isAdult?: (boolean | null);
    /**
     * If the media is officially licensed or a self-published doujin release
     */
    isLicensed?: (boolean | null);
    /**
     * Locked media may not be added to lists our favorited. This may be due to the entry pending for deletion or other reasons.
     */
    isLocked?: (boolean | null);
    /**
     * If the media is blocked from being recommended to/from
     */
    isRecommendationBlocked?: (boolean | null);
    /**
     * If the media is blocked from being reviewed
     */
    isReviewBlocked?: (boolean | null);
    /**
     * Mean score of all the user's scores of the media
     */
    meanScore?: (number | null);
    /**
     * The authenticated user's media list entry for the media
     */
    mediaListEntry?: (app__media__graphql_media_schema__MediaList | null);
    /**
     * Notes for site moderators
     */
    modNotes?: (string | null);
    /**
     * The media's next episode airing schedule
     */
    nextAiringEpisode?: (AiringSchedule | null);
    /**
     * The number of users with the media on their list
     */
    popularity?: (number | null);
    /**
     * The ranking of the media in a particular time span and format compared to other media
     */
    rankings?: (Array<(MediaRank | null)> | null);
    /**
     * User recommendations for similar media
     */
    recommendations?: (RecommendationConnection | null);
    /**
     * Other media in the same or connecting franchise
     */
    relations?: (MediaConnection | null);
    /**
     * User reviews of the media
     */
    reviews?: (ReviewConnection | null);
    /**
     * The season the media was initially released in
     */
    season?: (MediaSeason | null);
    /**
     * The year & season the media was initially released in
     */
    seasonInt?: (number | null);
    /**
     * The season year the media was initially released in
     */
    seasonYear?: (number | null);
    /**
     * The url for the media page on the AniList website
     */
    siteUrl?: (string | null);
    /**
     * Source type the media was adapted from.
     */
    source?: (MediaSource | null);
    /**
     * The staff who produced the media
     */
    staff?: (StaffConnection | null);
    /**
     * The first official release date of the media
     */
    startDate?: (FuzzyDate | null);
    stats?: (MediaStats | null);
    /**
     * The current releasing status of the media
     */
    status?: (MediaStatus | null);
    /**
     * Data and links to legal streaming episodes on external sites
     */
    streamingEpisodes?: (Array<(MediaStreamingEpisode | null)> | null);
    /**
     * The companies who produced the media
     */
    studios?: (StudioConnection | null);
    /**
     * Alternative titles of the media
     */
    synonyms?: (Array<(string | null)> | null);
    /**
     * List of tags that describes elements and themes of the media
     */
    tags?: (Array<(MediaTag | null)> | null);
    /**
     * The official titles of the media in various languages
     */
    title?: (app__media__graphql_media_schema__MediaTitle | null);
    /**
     * Media trailer or advertisement
     */
    trailer?: (MediaTrailer | null);
    /**
     * The amount of related activity in the past hour
     */
    trending?: (number | null);
    /**
     * The media's daily trend stats
     */
    trends?: (MediaTrendConnection | null);
    /**
     * The type of the media; anime or manga
     */
    type?: (MediaType | null);
    /**
     * When the media's data was last updated
     */
    updatedAt?: (number | null);
    /**
     * The amount of volumes the manga has when complete
     */
    volumes?: (number | null);
    __typename?: ("Media" | null);
};

export type app__media__graphql_media_schema__MediaCoverImage = {
    /**
     * Average #hex color of cover image
     */
    color?: (string | null);
    /**
     * The cover image url of the media at its largest size. If this size isn't available, large will be provided instead.
     */
    extraLarge?: (string | null);
    /**
     * The cover image url of the media at a large size
     */
    large?: (string | null);
    /**
     * The cover image url of the media at medium size
     */
    medium?: (string | null);
    __typename?: ("MediaCoverImage" | null);
};

/**
 * List of anime or manga
 */
export type app__media__graphql_media_schema__MediaList = {
    /**
     * Map of advanced scores with name keys
     */
    advancedScores?: (string | null);
    /**
     * When the entry was completed by the user
     */
    completedAt?: (FuzzyDate | null);
    /**
     * When the entry data was created
     */
    createdAt?: (number | null);
    /**
     * Map of booleans for which custom lists the entry are in
     */
    customLists?: (string | null);
    /**
     * If the entry shown be hidden from non-custom lists
     */
    hiddenFromStatusLists?: (boolean | null);
    /**
     * The id of the list entry
     */
    id: number;
    media?: (app__media__graphql_media_schema__Media | null);
    /**
     * The id of the media
     */
    mediaId: number;
    /**
     * Text notes
     */
    notes?: (string | null);
    /**
     * Priority of planning
     */
    priority?: (number | null);
    /**
     * If the entry should only be visible to authenticated user
     */
    private?: (boolean | null);
    /**
     * The amount of episodes/chapters consumed by the user
     */
    progress?: (number | null);
    /**
     * The amount of volumes read by the user
     */
    progressVolumes?: (number | null);
    /**
     * The amount of times the user has rewatched/read the media
     */
    repeat?: (number | null);
    /**
     * The score of the entry
     */
    score?: (number | null);
    /**
     * When the entry was started by the user
     */
    startedAt?: (FuzzyDate | null);
    /**
     * The watching/reading status
     */
    status?: (MediaListStatus | null);
    /**
     * When the entry data was last updated
     */
    updatedAt?: (number | null);
    user?: (User | null);
    /**
     * The id of the user owner of the list entry
     */
    userId: number;
    __typename?: ("MediaList" | null);
};

/**
 * The official titles of the media in various languages
 */
export type app__media__graphql_media_schema__MediaTitle = {
    /**
     * The official english title
     */
    english?: (string | null);
    /**
     * Official title in it's native language
     */
    native?: (string | null);
    /**
     * The romanization of the native language title
     */
    romaji?: (string | null);
    /**
     * The currently authenticated users preferred title language. Default romaji for non-authenticated
     */
    userPreferred?: (string | null);
    __typename?: ("MediaTitle" | null);
};

/**
 * Anime or Manga
 */
export type app__media__graphql_search_schema__Media = {
    /**
     * The id of the media
     */
    id: number;
    /**
     * The official titles of the media in various languages
     */
    title?: (app__media__graphql_search_schema__MediaTitle | null);
    /**
     * The cover images of the media
     */
    coverImage?: (app__media__graphql_search_schema__MediaCoverImage | null);
    /**
     * The type of the media; anime or manga
     */
    type?: (MediaType | null);
    /**
     * The format the media was released in
     */
    format?: (MediaFormat | null);
    /**
     * The current releasing status of the media
     */
    status?: (MediaStatus | null);
    /**
     * A weighted average score of all the user's scores of the media
     */
    averageScore?: (number | null);
    /**
     * The first official release date of the media
     */
    startDate?: (FuzzyDate | null);
};

export type app__media__graphql_search_schema__MediaCoverImage = {
    /**
     * The cover image url of the media at a large size
     */
    large?: (string | null);
    /**
     * The cover image url of the media at medium size
     */
    medium?: (string | null);
};

/**
 * The official titles of the media in various languages
 */
export type app__media__graphql_search_schema__MediaTitle = {
    /**
     * The official english title
     */
    english?: (string | null);
    /**
     * Official title in it's native language
     */
    native?: (string | null);
    /**
     * The romanization of the native language title
     */
    romaji?: (string | null);
};

/**
 * List of anime or manga.
 */
export type app__media__graphql_user_schema__MediaList = {
    /**
     * The id of the media
     */
    mediaId: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * A character that features in an anime or manga
 */
export type Character = {
    /**
     * The character's age. Note this is a string, not an int, it may contain further text and additional ages.
     */
    age?: (string | null);
    /**
     * The characters blood type
     */
    bloodType?: (string | null);
    /**
     * The character's birth date
     */
    dateOfBirth?: (FuzzyDate | null);
    /**
     * A general description of the character
     */
    description?: (string | null);
    /**
     * The amount of user's who have favourited the character
     */
    favourites?: (number | null);
    /**
     * The character's gender. Usually Male, Female, or Non-binary but can be any string.
     */
    gender?: (string | null);
    /**
     * The id of the character
     */
    id: number;
    /**
     * Character images
     */
    image?: (CharacterImage | null);
    /**
     * Media that includes the character
     */
    media?: (MediaConnection | null);
    /**
     * Notes for site moderators
     */
    modNotes?: (string | null);
    /**
     * The names of the character
     */
    name?: (CharacterName | null);
    /**
     * The url for the character page on the AniList website
     */
    siteUrl?: (string | null);
    updatedAt?: (number | null);
    __typename?: ("Character" | null);
};

export type CharacterConnection = {
    edges?: (Array<(CharacterEdge | null)> | null);
    nodes?: (Array<(Character | null)> | null);
    /**
     * The pagination information
     */
    pageInfo?: (PageInfo | null);
    __typename?: ("CharacterConnection" | null);
};

/**
 * Character connection edge
 */
export type CharacterEdge = {
    /**
     * The order the character should be displayed from the users favourites
     */
    favouriteOrder?: (number | null);
    /**
     * The id of the connection
     */
    id?: (number | null);
    /**
     * The media the character is in
     */
    media?: (Array<(app__media__graphql_media_schema__Media | null)> | null);
    /**
     * Media specific character name
     */
    name?: (string | null);
    node?: (Character | null);
    /**
     * The characters role in the media
     */
    role?: (CharacterRole | null);
    /**
     * The voice actors of the character with role date
     */
    voiceActorRoles?: (Array<(StaffRoleType | null)> | null);
    /**
     * The voice actors of the character
     */
    voiceActors?: (Array<(Staff | null)> | null);
    __typename?: ("CharacterEdge" | null);
};

export type CharacterImage = {
    /**
     * The character's image of media at its largest size
     */
    large?: (string | null);
    /**
     * The character's image of media at medium size
     */
    medium?: (string | null);
    __typename?: ("CharacterImage" | null);
};

/**
 * The names of the character
 */
export type CharacterName = {
    /**
     * Other names the character might be referred to as
     */
    alternative?: (Array<(string | null)> | null);
    /**
     * Other names the character might be referred to as but are spoilers
     */
    alternativeSpoiler?: (Array<(string | null)> | null);
    /**
     * The character's given name
     */
    first?: (string | null);
    /**
     * The character's first and last name
     */
    full?: (string | null);
    /**
     * The character's surname
     */
    last?: (string | null);
    /**
     * The character's middle name
     */
    middle?: (string | null);
    /**
     * The character's full name in their native language
     */
    native?: (string | null);
    /**
     * The currently authenticated users preferred name language. Default romaji for non-authenticated
     */
    userPreferred?: (string | null);
    __typename?: ("CharacterName" | null);
};

/**
 * The role the character plays in the media
 */
export type CharacterRole = 'BACKGROUND' | 'MAIN' | 'SUPPORTING';

export type ExternalLinkType = 'INFO' | 'SOCIAL' | 'STREAMING';

/**
 * User's favourite anime, manga, characters, staff & studios
 */
export type Favourites = {
    /**
     * Favourite anime
     */
    anime?: (MediaConnection | null);
    /**
     * Favourite characters
     */
    characters?: (CharacterConnection | null);
    /**
     * Favourite manga
     */
    manga?: (MediaConnection | null);
    /**
     * Favourite staff
     */
    staff?: (StaffConnection | null);
    /**
     * Favourite studios
     */
    studios?: (StudioConnection | null);
    __typename?: ("Favourites" | null);
};

/**
 * User's format statistics
 */
export type FormatStats = {
    amount?: (number | null);
    format?: (MediaFormat | null);
    __typename?: ("FormatStats" | null);
};

/**
 * Date object that allows for incomplete date values (fuzzy)
 */
export type FuzzyDate = {
    /**
     * Numeric Day (24)
     */
    day?: (number | null);
    /**
     * Numeric Month (3)
     */
    month?: (number | null);
    /**
     * Numeric Year (2017)
     */
    year?: (number | null);
    __typename?: ("FuzzyDate" | null);
};

/**
 * User's genre statistics
 */
export type GenreStats = {
    amount?: (number | null);
    genre?: (string | null);
    meanScore?: (number | null);
    /**
     * The amount of time in minutes the genre has been watched by the user
     */
    timeWatched?: (number | null);
    __typename?: ("GenreStats" | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type ListActivityOption = {
    disabled?: (boolean | null);
    type?: (MediaListStatus | null);
    __typename?: ("ListActivityOption" | null);
};

/**
 * User's list score statistics
 */
export type ListScoreStats = {
    meanScore?: (number | null);
    standardDeviation?: (number | null);
    __typename?: ("ListScoreStats" | null);
};

export type MediaConnection = {
    edges?: (Array<(MediaEdge | null)> | null);
    nodes?: (Array<(app__media__graphql_media_schema__Media | null)> | null);
    /**
     * The pagination information
     */
    pageInfo?: (PageInfo | null);
    __typename?: ("MediaConnection" | null);
};

/**
 * Media connection edge
 */
export type MediaEdge = {
    /**
     * Media specific character name
     */
    characterName?: (string | null);
    /**
     * The characters role in the media
     */
    characterRole?: (CharacterRole | null);
    /**
     * The characters in the media voiced by the parent actor
     */
    characters?: (Array<(Character | null)> | null);
    /**
     * Used for grouping roles where multiple dubs exist for the same language. Either dubbing company name or language variant.
     */
    dubGroup?: (string | null);
    /**
     * The order the media should be displayed from the users favourites
     */
    favouriteOrder?: (number | null);
    /**
     * The id of the connection
     */
    id?: (number | null);
    /**
     * If the studio is the main animation studio of the media (For Studio->MediaConnection field only)
     */
    isMainStudio: boolean;
    node?: (app__media__graphql_media_schema__Media | null);
    /**
     * The type of relation to the parent model
     */
    relationType?: (MediaRelation | null);
    /**
     * Notes regarding the VA's role for the character
     */
    roleNotes?: (string | null);
    /**
     * The role of the staff member in the production of the media
     */
    staffRole?: (string | null);
    /**
     * The voice actors of the character with role date
     */
    voiceActorRoles?: (Array<(StaffRoleType | null)> | null);
    /**
     * The voice actors of the character
     */
    voiceActors?: (Array<(Staff | null)> | null);
    __typename?: ("MediaEdge" | null);
};

/**
 * An external link to another site related to the media or staff member
 */
export type MediaExternalLink = {
    color?: (string | null);
    /**
     * The icon image url of the site. Not available for all links. Transparent PNG 64x64
     */
    icon?: (string | null);
    /**
     * The id of the external link
     */
    id: number;
    isDisabled?: (boolean | null);
    /**
     * Language the site content is in. See Staff language field for values.
     */
    language?: (string | null);
    notes?: (string | null);
    /**
     * The links website site name
     */
    site: string;
    /**
     * The links website site id
     */
    siteId?: (number | null);
    type?: (ExternalLinkType | null);
    /**
     * The url of the external link or base url of link source
     */
    url?: (string | null);
    __typename?: ("MediaExternalLink" | null);
};

/**
 * The format the media was released in
 */
export type MediaFormat = 'MANGA' | 'MOVIE' | 'MUSIC' | 'NOVEL' | 'ONA' | 'ONE_SHOT' | 'OVA' | 'SPECIAL' | 'TV' | 'TV_SHORT';

/**
 * List of anime or manga.
 */
export type MediaListCollection = {
    /**
     * Grouped media list entries
     */
    lists?: (Array<(MediaListGroup | null)> | null);
};

/**
 * List group of anime or manga entries.
 */
export type MediaListGroup = {
    /**
     * Media list entries
     */
    entries?: (Array<(app__media__graphql_user_schema__MediaList | null)> | null);
    status?: (MediaListStatus | null);
};

/**
 * A user's list options
 */
export type MediaListOptions = {
    /**
     * The user's anime list options
     */
    animeList?: (MediaListTypeOptions | null);
    /**
     * The user's manga list options
     */
    mangaList?: (MediaListTypeOptions | null);
    /**
     * The default order list rows should be displayed in
     */
    rowOrder?: (string | null);
    /**
     * The score format the user is using for media lists
     */
    scoreFormat?: (ScoreFormat | null);
    /**
     * The list theme options for both lists
     */
    sharedTheme?: (string | null);
    /**
     * If the shared theme should be used instead of the individual list themes
     */
    sharedThemeEnabled?: (boolean | null);
    useLegacyLists?: (boolean | null);
    __typename?: ("MediaListOptions" | null);
};

/**
 * Media list watching/reading status enum.
 */
export type MediaListStatus = 'COMPLETED' | 'CURRENT' | 'DROPPED' | 'PAUSED' | 'PLANNING' | 'REPEATING';

/**
 * A user's list options for anime or manga lists
 */
export type MediaListTypeOptions = {
    /**
     * The names of the user's advanced scoring sections
     */
    advancedScoring?: (Array<(string | null)> | null);
    /**
     * If advanced scoring is enabled
     */
    advancedScoringEnabled?: (boolean | null);
    /**
     * The names of the user's custom lists
     */
    customLists?: (Array<(string | null)> | null);
    /**
     * The order each list should be displayed in
     */
    sectionOrder?: (Array<(string | null)> | null);
    /**
     * If the completed sections of the list should be separated by format
     */
    splitCompletedSectionByFormat?: (boolean | null);
    /**
     * The list theme options
     */
    theme?: (string | null);
    __typename?: ("MediaListTypeOptions" | null);
};

/**
 * The ranking of a media in a particular time span and format compared to other media
 */
export type MediaRank = {
    /**
     * If the ranking is based on all time instead of a season/year
     */
    allTime?: (boolean | null);
    /**
     * String that gives context to the ranking type and time span
     */
    context: string;
    /**
     * The format the media is ranked within
     */
    format: MediaFormat;
    /**
     * The id of the rank
     */
    id: number;
    /**
     * The numerical rank of the media
     */
    rank: number;
    /**
     * The season the media is ranked within
     */
    season?: (MediaSeason | null);
    type: MediaRankType;
    /**
     * The year the media is ranked within
     */
    year?: (number | null);
    __typename?: ("MediaRank" | null);
};

/**
 * The type of ranking
 */
export type MediaRankType = 'POPULAR' | 'RATED';

/**
 * Type of relation media has to its parent.
 */
export type MediaRelation = 'ADAPTATION' | 'ALTERNATIVE' | 'CHARACTER' | 'COMPILATION' | 'CONTAINS' | 'OTHER' | 'PARENT' | 'PREQUEL' | 'SEQUEL' | 'SIDE_STORY' | 'SOURCE' | 'SPIN_OFF' | 'SUMMARY';

export type MediaSeason = 'FALL' | 'SPRING' | 'SUMMER' | 'WINTER';

/**
 * Source type the media was adapted from
 */
export type MediaSource = 'ANIME' | 'COMIC' | 'DOUJINSHI' | 'GAME' | 'LIGHT_NOVEL' | 'LIVE_ACTION' | 'MANGA' | 'MULTIMEDIA_PROJECT' | 'NOVEL' | 'ORIGINAL' | 'OTHER' | 'PICTURE_BOOK' | 'VIDEO_GAME' | 'VISUAL_NOVEL' | 'WEB_NOVEL';

/**
 * A media's statistics
 */
export type MediaStats = {
    airingProgression?: (Array<(AiringProgression | null)> | null);
    scoreDistribution?: (Array<(ScoreDistribution | null)> | null);
    statusDistribution?: (Array<(StatusDistribution | null)> | null);
    __typename?: ("MediaStats" | null);
};

/**
 * The current releasing status of the media
 */
export type MediaStatus = 'CANCELLED' | 'FINISHED' | 'HIATUS' | 'NOT_YET_RELEASED' | 'RELEASING';

/**
 * Data and links to legal streaming episodes on external sites
 */
export type MediaStreamingEpisode = {
    /**
     * The site location of the streaming episodes
     */
    site?: (string | null);
    /**
     * Url of episode image thumbnail
     */
    thumbnail?: (string | null);
    /**
     * Title of the episode
     */
    title?: (string | null);
    /**
     * The url of the episode
     */
    url?: (string | null);
    __typename?: ("MediaStreamingEpisode" | null);
};

/**
 * A tag that describes a theme or element of the media
 */
export type MediaTag = {
    /**
     * The categories of tags this tag belongs to
     */
    category?: (string | null);
    /**
     * A general description of the tag
     */
    description?: (string | null);
    /**
     * The id of the tag
     */
    id: number;
    /**
     * If the tag is only for adult 18+ media
     */
    isAdult?: (boolean | null);
    /**
     * If the tag could be a spoiler for any media
     */
    isGeneralSpoiler?: (boolean | null);
    /**
     * If the tag is a spoiler for this media
     */
    isMediaSpoiler?: (boolean | null);
    /**
     * The name of the tag
     */
    name: string;
    /**
     * The relevance ranking of the tag out of the 100 for this media
     */
    rank?: (number | null);
    /**
     * The user who submitted the tag
     */
    userId?: (number | null);
    __typename?: ("MediaTag" | null);
};

/**
 * Media trailer or advertisement
 */
export type MediaTrailer = {
    /**
     * The trailer video id
     */
    id?: (string | null);
    /**
     * The site the video is hosted by (Currently either youtube or dailymotion)
     */
    site?: (string | null);
    /**
     * The url for the thumbnail image of the video
     */
    thumbnail?: (string | null);
    __typename?: ("MediaTrailer" | null);
};

/**
 * Daily media statistics
 */
export type MediaTrend = {
    /**
     * A weighted average score of all the user's scores of the media
     */
    averageScore?: (number | null);
    /**
     * The day the data was recorded (timestamp)
     */
    date: number;
    /**
     * The episode number of the anime released on this day
     */
    episode?: (number | null);
    /**
     * The number of users with watching/reading the media
     */
    inProgress?: (number | null);
    /**
     * The related media
     */
    media?: (app__media__graphql_media_schema__Media | null);
    /**
     * The id of the tag
     */
    mediaId: number;
    /**
     * The number of users with the media on their list
     */
    popularity?: (number | null);
    /**
     * If the media was being released at this time
     */
    releasing: boolean;
    /**
     * The amount of media activity on the day
     */
    trending: number;
    __typename?: ("MediaTrend" | null);
};

export type MediaTrendConnection = {
    edges?: (Array<(MediaTrendEdge | null)> | null);
    nodes?: (Array<(MediaTrend | null)> | null);
    /**
     * The pagination information
     */
    pageInfo?: (PageInfo | null);
    __typename?: ("MediaTrendConnection" | null);
};

/**
 * Media trend connection edge
 */
export type MediaTrendEdge = {
    node?: (MediaTrend | null);
    __typename?: ("MediaTrendEdge" | null);
};

/**
 * Media type enum, anime or manga.
 */
export type MediaType = 'ANIME' | 'MANGA';

export type Message = {
    message: string;
};

/**
 * Mod role enums
 */
export type ModRole = 'ADMIN' | 'ANIME_DATA' | 'CHARACTER_DATA' | 'COMMUNITY' | 'DEVELOPER' | 'DISCORD_COMMUNITY' | 'LEAD_ANIME_DATA' | 'LEAD_COMMUNITY' | 'LEAD_DEVELOPER' | 'LEAD_MANGA_DATA' | 'LEAD_SOCIAL_MEDIA' | 'MANGA_DATA' | 'RETIRED' | 'SOCIAL_MEDIA' | 'STAFF_DATA';

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Notification option
 */
export type NotificationOption = {
    /**
     * Whether this type of notification is enabled
     */
    enabled?: (boolean | null);
    /**
     * The type of notification
     */
    type?: (NotificationType | null);
    __typename?: ("NotificationOption" | null);
};

/**
 * Notification type enum
 */
export type NotificationType = 'ACTIVITY_LIKE' | 'ACTIVITY_MENTION' | 'ACTIVITY_MESSAGE' | 'ACTIVITY_REPLY' | 'ACTIVITY_REPLY_LIKE' | 'ACTIVITY_REPLY_SUBSCRIBED' | 'AIRING' | 'FOLLOWING' | 'MEDIA_DATA_CHANGE' | 'MEDIA_DELETION' | 'MEDIA_MERGE' | 'RELATED_MEDIA_ADDITION' | 'THREAD_COMMENT_LIKE' | 'THREAD_COMMENT_MENTION' | 'THREAD_COMMENT_REPLY' | 'THREAD_LIKE' | 'THREAD_SUBSCRIBED';

export type PageInfo = {
    /**
     * The current page
     */
    currentPage?: (number | null);
    /**
     * If there is another page
     */
    hasNextPage?: (boolean | null);
    /**
     * The last page
     */
    lastPage?: (number | null);
    /**
     * The count on a page
     */
    perPage?: (number | null);
    /**
     * The total number of items. Note: This value is not guaranteed to be accurate, do not rely on this for logic
     */
    total?: (number | null);
    __typename?: ("PageInfo" | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Media recommendation
 */
export type Recommendation = {
    /**
     * The id of the recommendation
     */
    id: number;
    /**
     * The media the recommendation is from
     */
    media?: (app__media__graphql_media_schema__Media | null);
    /**
     * The recommended media
     */
    mediaRecommendation?: (app__media__graphql_media_schema__Media | null);
    /**
     * Users rating of the recommendation
     */
    rating?: (number | null);
    /**
     * The user that first created the recommendation
     */
    user?: (User | null);
    /**
     * The rating of the recommendation by currently authenticated user
     */
    userRating?: (RecommendationRating | null);
    __typename?: ("Recommendation" | null);
};

export type RecommendationConnection = {
    edges?: (Array<(RecommendationEdge | null)> | null);
    nodes?: (Array<(Recommendation | null)> | null);
    /**
     * The pagination information
     */
    pageInfo?: (PageInfo | null);
    __typename?: ("RecommendationConnection" | null);
};

/**
 * Recommendation connection edge
 */
export type RecommendationEdge = {
    node?: (Recommendation | null);
    __typename?: ("RecommendationEdge" | null);
};

/**
 * Recommendation rating enums
 */
export type RecommendationRating = 'NO_RATING' | 'RATE_DOWN' | 'RATE_UP';

/**
 * A Review that features in an anime or manga
 */
export type Review = {
    /**
     * The main review body text
     */
    body?: (string | null);
    /**
     * The time of the thread creation
     */
    createdAt: number;
    /**
     * The id of the review
     */
    id: number;
    /**
     * The media the review is of
     */
    media?: (app__media__graphql_media_schema__Media | null);
    /**
     * The id of the review's media
     */
    mediaId: number;
    /**
     * For which type of media the review is for
     */
    mediaType?: (MediaType | null);
    /**
     * If the review is not yet publicly published and is only viewable by creator
     */
    private?: (boolean | null);
    /**
     * The total user rating of the review
     */
    rating?: (number | null);
    /**
     * The amount of user ratings of the review
     */
    ratingAmount?: (number | null);
    /**
     * The review score of the media
     */
    score?: (number | null);
    /**
     * The url for the review page on the AniList website
     */
    siteUrl?: (string | null);
    /**
     * A short summary of the review
     */
    summary?: (string | null);
    /**
     * The time of the thread last update
     */
    updatedAt: number;
    /**
     * The creator of the review
     */
    user?: (User | null);
    /**
     * The id of the review's creator
     */
    userId: number;
    /**
     * The rating of the review by currently authenticated user
     */
    userRating?: (ReviewRating | null);
    __typename?: ("Review" | null);
};

export type ReviewConnection = {
    edges?: (Array<(ReviewEdge | null)> | null);
    nodes?: (Array<(Review | null)> | null);
    /**
     * The pagination information
     */
    pageInfo?: (PageInfo | null);
    __typename?: ("ReviewConnection" | null);
};

/**
 * Review connection edge
 */
export type ReviewEdge = {
    node?: (Review | null);
    __typename?: ("ReviewEdge" | null);
};

/**
 * Review rating enums
 */
export type ReviewRating = 'DOWN_VOTE' | 'NO_VOTE' | 'UP_VOTE';

/**
 * A user's list score distribution.
 */
export type ScoreDistribution = {
    /**
     * The amount of list entries with this score
     */
    amount?: (number | null);
    score?: (number | null);
    __typename?: ("ScoreDistribution" | null);
};

/**
 * Media list scoring type
 */
export type ScoreFormat = 'POINT_10' | 'POINT_100' | 'POINT_10_DECIMAL' | 'POINT_3' | 'POINT_5';

/**
 * Search page response.
 */
export type SearchPage = {
    /**
     * The pagination information
     */
    pageInfo?: (PageInfo | null);
    media?: (Array<(app__media__graphql_search_schema__Media | null)> | null);
};

/**
 * Voice actors or production staff
 */
export type Staff = {
    /**
     * The person's age in years
     */
    age?: (number | null);
    /**
     * The persons blood type
     */
    bloodType?: (string | null);
    /**
     * Media the actor voiced characters in. (Same data as characters with media as node instead of characters)
     */
    characterMedia?: (MediaConnection | null);
    /**
     * Characters voiced by the actor
     */
    characters?: (CharacterConnection | null);
    dateOfBirth?: (FuzzyDate | null);
    dateOfDeath?: (FuzzyDate | null);
    /**
     * A general description of the staff member
     */
    description?: (string | null);
    /**
     * The amount of user's who have favourited the staff member
     */
    favourites?: (number | null);
    /**
     * The staff's gender. Usually Male, Female, or Non-binary but can be any string.
     */
    gender?: (string | null);
    /**
     * The persons birthplace or hometown
     */
    homeTown?: (string | null);
    /**
     * The id of the staff member
     */
    id: number;
    /**
     * The staff images
     */
    image?: (StaffImage | null);
    /**
     * The primary language the staff member dub's in
     */
    language?: (StaffLanguage | null);
    /**
     * The primary language of the staff member. Current values: Japanese, English, Korean, Italian, Spanish, Portuguese, French, German, Hebrew, Hungarian, Chinese, Arabic, Filipino, Catalan, Finnish, Turkish, Dutch, Swedish, Thai, Tagalog, Malaysian, Indonesian, Vietnamese, Nepali, Hindi, Urdu
     */
    languageV2?: (string | null);
    /**
     * Notes for site moderators
     */
    modNotes?: (string | null);
    /**
     * The names of the staff member
     */
    name?: (StaffName | null);
    /**
     * The person's primary occupations
     */
    primaryOccupations?: (Array<(string | null)> | null);
    /**
     * The url for the staff page on the AniList website
     */
    siteUrl?: (string | null);
    /**
     * Staff member that the submission is referencing
     */
    staff?: (Staff | null);
    /**
     * Media where the staff member has a production role
     */
    staffMedia?: (MediaConnection | null);
    /**
     * Inner details of submission status
     */
    submissionNotes?: (string | null);
    /**
     * Status of the submission
     */
    submissionStatus?: (number | null);
    /**
     * Submitter for the submission
     */
    submitter?: (User | null);
    updatedAt?: (number | null);
    /**
     * [startYear, endYear] (If the 2nd value is not present staff is still active)
     */
    yearsActive?: (Array<(number | null)> | null);
    __typename?: ("Staff" | null);
};

export type StaffConnection = {
    edges?: (Array<(StaffEdge | null)> | null);
    nodes?: (Array<(Staff | null)> | null);
    /**
     * The pagination information
     */
    pageInfo?: (PageInfo | null);
    __typename?: ("StaffConnection" | null);
};

/**
 * Staff connection edge
 */
export type StaffEdge = {
    /**
     * The order the staff should be displayed from the users favourites
     */
    favouriteOrder?: (number | null);
    /**
     * The id of the connection
     */
    id?: (number | null);
    node?: (Staff | null);
    /**
     * The role of the staff member in the production of the media
     */
    role?: (string | null);
    __typename?: ("StaffEdge" | null);
};

export type StaffImage = {
    /**
     * The person's image of media at its largest size
     */
    large?: (string | null);
    /**
     * The person's image of media at medium size
     */
    medium?: (string | null);
    __typename?: ("StaffImage" | null);
};

/**
 * The primary language of the voice actor
 */
export type StaffLanguage = 'ENGLISH' | 'FRENCH' | 'GERMAN' | 'HEBREW' | 'HUNGARIAN' | 'ITALIAN' | 'JAPANESE' | 'KOREAN' | 'PORTUGUESE' | 'SPANISH';

/**
 * The names of the staff member
 */
export type StaffName = {
    /**
     * Other names the staff member might be referred to as (pen names)
     */
    alternative?: (Array<(string | null)> | null);
    /**
     * The person's given name
     */
    first?: (string | null);
    /**
     * The person's first and last name
     */
    full?: (string | null);
    /**
     * The person's surname
     */
    last?: (string | null);
    /**
     * The person's middle name
     */
    middle?: (string | null);
    /**
     * The person's full name in their native language
     */
    native?: (string | null);
    /**
     * The currently authenticated users preferred name language. Default romaji for non-authenticated
     */
    userPreferred?: (string | null);
    __typename?: ("StaffName" | null);
};

/**
 * Voice actor role for a character
 */
export type StaffRoleType = {
    /**
     * Used for grouping roles where multiple dubs exist for the same language. Either dubbing company name or language variant.
     */
    dubGroup?: (string | null);
    /**
     * Notes regarding the VA's role for the character
     */
    roleNotes?: (string | null);
    /**
     * The voice actors of the character
     */
    voiceActor?: (Staff | null);
    __typename?: ("StaffRoleType" | null);
};

/**
 * User's staff statistics
 */
export type StaffStats = {
    amount?: (number | null);
    meanScore?: (number | null);
    staff?: (Staff | null);
    /**
     * The amount of time in minutes the staff member has been watched by the user
     */
    timeWatched?: (number | null);
    __typename?: ("StaffStats" | null);
};

/**
 * The distribution of the watching/reading status of media or a user's list
 */
export type StatusDistribution = {
    /**
     * The amount of entries with this status
     */
    amount?: (number | null);
    /**
     * The day the activity took place (Unix timestamp)
     */
    status?: (MediaListStatus | null);
    __typename?: ("StatusDistribution" | null);
};

/**
 * Animation or production company
 */
export type Studio = {
    /**
     * The amount of user's who have favourited the studio
     */
    favourites?: (number | null);
    /**
     * The id of the studio
     */
    id: number;
    /**
     * If the studio is an animation studio or a different kind of company
     */
    isAnimationStudio: boolean;
    /**
     * The media the studio has worked on
     */
    media?: (MediaConnection | null);
    /**
     * The name of the studio
     */
    name: string;
    /**
     * The url for the studio page on the AniList website
     */
    siteUrl?: (string | null);
    __typename?: ("Studio" | null);
};

export type StudioConnection = {
    edges?: (Array<(StudioEdge | null)> | null);
    nodes?: (Array<(Studio | null)> | null);
    /**
     * The pagination information
     */
    pageInfo?: (PageInfo | null);
    __typename?: ("StudioConnection" | null);
};

/**
 * Studio connection edge
 */
export type StudioEdge = {
    /**
     * The order the character should be displayed from the users favourites
     */
    favouriteOrder?: (number | null);
    /**
     * The id of the connection
     */
    id?: (number | null);
    /**
     * If the studio is the main animation studio of the anime
     */
    isMain: boolean;
    node?: (Studio | null);
    __typename?: ("StudioEdge" | null);
};

/**
 * User's studio statistics
 */
export type StudioStats = {
    amount?: (number | null);
    meanScore?: (number | null);
    studio?: (Studio | null);
    /**
     * The amount of time in minutes the studio's works have been watched by the user
     */
    timeWatched?: (number | null);
    __typename?: ("StudioStats" | null);
};

/**
 * User's tag statistics
 */
export type TagStats = {
    amount?: (number | null);
    meanScore?: (number | null);
    tag?: (MediaTag | null);
    /**
     * The amount of time in minutes the tag has been watched by the user
     */
    timeWatched?: (number | null);
    __typename?: ("TagStats" | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * A user
 */
export type User = {
    /**
     * The bio written by user (Markdown)
     */
    about?: (string | null);
    /**
     * The user's avatar images
     */
    avatar?: (UserAvatar | null);
    /**
     * The user's banner images
     */
    bannerImage?: (string | null);
    bans?: (string | null);
    /**
     * When the user's account was created. (Does not exist for accounts created before 2020)
     */
    createdAt?: (number | null);
    /**
     * Custom donation badge text
     */
    donatorBadge?: (string | null);
    /**
     * The donation tier of the user
     */
    donatorTier?: (number | null);
    /**
     * The users favourites
     */
    favourites?: (Favourites | null);
    /**
     * The id of the user
     */
    id: number;
    /**
     * If the user is blocked by the authenticated user
     */
    isBlocked?: (boolean | null);
    /**
     * If this user if following the authenticated user
     */
    isFollower?: (boolean | null);
    /**
     * If the authenticated user if following this user
     */
    isFollowing?: (boolean | null);
    /**
     * The user's media list options
     */
    mediaListOptions?: (MediaListOptions | null);
    /**
     * The user's moderator roles if they are a site moderator
     */
    moderatorRoles?: (Array<(ModRole | null)> | null);
    /**
     * If the user is a moderator or data moderator
     */
    moderatorStatus?: (string | null);
    /**
     * The name of the user
     */
    name: string;
    /**
     * The user's general options
     */
    options?: (UserOptions | null);
    /**
     * The user's previously used names.
     */
    previousNames?: (Array<(UserPreviousName | null)> | null);
    /**
     * The url for the user page on the AniList website
     */
    siteUrl?: (string | null);
    /**
     * The users anime & manga list statistics
     */
    statistics?: (UserStatisticTypes | null);
    /**
     * The user's statistics
     */
    stats?: (UserStats | null);
    /**
     * The number of unread notifications the user has
     */
    unreadNotificationCount?: (number | null);
    /**
     * When the user's data was last updated
     */
    updatedAt?: (number | null);
    __typename?: ("User" | null);
};

/**
 * A user's activity history stats.
 */
export type UserActivityHistory = {
    /**
     * The amount of activity on the day
     */
    amount?: (number | null);
    /**
     * The day the activity took place (Unix timestamp)
     */
    date?: (number | null);
    /**
     * The level of activity represented on a 1-10 scale
     */
    level?: (number | null);
    __typename?: ("UserActivityHistory" | null);
};

/**
 * A user's avatars
 */
export type UserAvatar = {
    /**
     * The avatar of user at its largest size
     */
    large?: (string | null);
    /**
     * The avatar of user at medium size
     */
    medium?: (string | null);
    __typename?: ("UserAvatar" | null);
};

export type UserCountryStatistic = {
    chaptersRead: number;
    count: number;
    country?: (string | null);
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    __typename?: ("UserCountryStatistic" | null);
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserFormatStatistic = {
    chaptersRead: number;
    count: number;
    format?: (MediaFormat | null);
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    __typename?: ("UserFormatStatistic" | null);
};

export type UserGenreStatistic = {
    chaptersRead: number;
    count: number;
    genre?: (string | null);
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    __typename?: ("UserGenreStatistic" | null);
};

export type UserLengthStatistic = {
    chaptersRead: number;
    count: number;
    length?: (string | null);
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    __typename?: ("UserLengthStatistic" | null);
};

/**
 * A user's general options
 */
export type UserOptions = {
    /**
     * Minutes between activity for them to be merged together. 0 is Never, Above 2 weeks (20160 mins) is Always.
     */
    activityMergeTime?: (number | null);
    /**
     * Whether the user receives notifications when a show they are watching aires
     */
    airingNotifications?: (boolean | null);
    /**
     * The list activity types the user has disabled from being created from list updates
     */
    disabledListActivity?: (Array<(ListActivityOption | null)> | null);
    /**
     * Whether the user has enabled viewing of 18+ content
     */
    displayAdultContent?: (boolean | null);
    /**
     * Notification options
     */
    notificationOptions?: (Array<(NotificationOption | null)> | null);
    /**
     * Profile highlight color (blue, purple, pink, orange, red, green, gray)
     */
    profileColor?: (string | null);
    /**
     * Whether the user only allow messages from users they follow
     */
    restrictMessagesToFollowing?: (boolean | null);
    /**
     * The language the user wants to see staff and character names in
     */
    staffNameLanguage?: (UserStaffNameLanguage | null);
    /**
     * The user's timezone offset (Auth user only)
     */
    timezone?: (string | null);
    /**
     * The language the user wants to see media titles in
     */
    titleLanguage?: (UserTitleLanguage | null);
    __typename?: ("UserOptions" | null);
};

/**
 * A user's previous name
 */
export type UserPreviousName = {
    /**
     * When the user first changed from this name.
     */
    createdAt?: (number | null);
    /**
     * A previous name of the user.
     */
    name?: (string | null);
    /**
     * When the user most recently changed from this name.
     */
    updatedAt?: (number | null);
    __typename?: ("UserPreviousName" | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserReleaseYearStatistic = {
    chaptersRead: number;
    count: number;
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    releaseYear?: (number | null);
    __typename?: ("UserReleaseYearStatistic" | null);
};

export type UserScoreStatistic = {
    chaptersRead: number;
    count: number;
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    score?: (number | null);
    __typename?: ("UserScoreStatistic" | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * The language the user wants to see staff and character names in
 */
export type UserStaffNameLanguage = 'NATIVE' | 'ROMAJI' | 'ROMAJI_WESTERN';

export type UserStaffStatistic = {
    chaptersRead: number;
    count: number;
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    staff?: (Staff | null);
    __typename?: ("UserStaffStatistic" | null);
};

export type UserStartYearStatistic = {
    chaptersRead: number;
    count: number;
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    startYear?: (number | null);
    __typename?: ("UserStartYearStatistic" | null);
};

export type UserStatistics = {
    chaptersRead: number;
    count: number;
    countries?: (Array<(UserCountryStatistic | null)> | null);
    episodesWatched: number;
    formats?: (Array<(UserFormatStatistic | null)> | null);
    genres?: (Array<(UserGenreStatistic | null)> | null);
    lengths?: (Array<(UserLengthStatistic | null)> | null);
    meanScore: number;
    minutesWatched: number;
    releaseYears?: (Array<(UserReleaseYearStatistic | null)> | null);
    scores?: (Array<(UserScoreStatistic | null)> | null);
    staff?: (Array<(UserStaffStatistic | null)> | null);
    standardDeviation: number;
    startYears?: (Array<(UserStartYearStatistic | null)> | null);
    statuses?: (Array<(UserStatusStatistic | null)> | null);
    studios?: (Array<(UserStudioStatistic | null)> | null);
    tags?: (Array<(UserTagStatistic | null)> | null);
    voiceActors?: (Array<(UserVoiceActorStatistic | null)> | null);
    volumesRead: number;
    __typename?: ("UserStatistics" | null);
};

export type UserStatisticTypes = {
    anime?: (UserStatistics | null);
    manga?: (UserStatistics | null);
    __typename?: ("UserStatisticTypes" | null);
};

/**
 * A user's statistics
 */
export type UserStats = {
    activityHistory?: (Array<(UserActivityHistory | null)> | null);
    animeListScores?: (ListScoreStats | null);
    animeScoreDistribution?: (Array<(ScoreDistribution | null)> | null);
    animeStatusDistribution?: (Array<(StatusDistribution | null)> | null);
    /**
     * The amount of manga chapters the user has read
     */
    chaptersRead?: (number | null);
    favouredActors?: (Array<(StaffStats | null)> | null);
    favouredFormats?: (Array<(FormatStats | null)> | null);
    favouredGenres?: (Array<(GenreStats | null)> | null);
    favouredGenresOverview?: (Array<(GenreStats | null)> | null);
    favouredStaff?: (Array<(StaffStats | null)> | null);
    favouredStudios?: (Array<(StudioStats | null)> | null);
    favouredTags?: (Array<(TagStats | null)> | null);
    favouredYears?: (Array<(YearStats | null)> | null);
    mangaListScores?: (ListScoreStats | null);
    mangaScoreDistribution?: (Array<(ScoreDistribution | null)> | null);
    mangaStatusDistribution?: (Array<(StatusDistribution | null)> | null);
    /**
     * The amount of anime the user has watched in minutes
     */
    watchedTime?: (number | null);
    __typename?: ("UserStats" | null);
};

export type UserStatusStatistic = {
    chaptersRead: number;
    count: number;
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    status?: (MediaListStatus | null);
    __typename?: ("UserStatusStatistic" | null);
};

export type UserStudioStatistic = {
    chaptersRead: number;
    count: number;
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    studio?: (Studio | null);
    __typename?: ("UserStudioStatistic" | null);
};

export type UserTagStatistic = {
    chaptersRead: number;
    count: number;
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    tag?: (MediaTag | null);
    __typename?: ("UserTagStatistic" | null);
};

/**
 * The language the user wants to see media titles in
 */
export type UserTitleLanguage = 'ENGLISH' | 'ENGLISH_STYLISED' | 'NATIVE' | 'NATIVE_STYLISED' | 'ROMAJI' | 'ROMAJI_STYLISED';

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type UserVoiceActorStatistic = {
    chaptersRead: number;
    characterIds: Array<(number | null)>;
    count: number;
    meanScore: number;
    mediaIds: Array<(number | null)>;
    minutesWatched: number;
    voiceActor?: (Staff | null);
    __typename?: ("UserVoiceActorStatistic" | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * User's year statistics
 */
export type YearStats = {
    amount?: (number | null);
    meanScore?: (number | null);
    year?: (number | null);
    __typename?: ("YearStats" | null);
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    itemId: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    itemId: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    itemId: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaReadMediaData = {
    mediaId: number;
};

export type MediaReadMediaResponse = (app__media__graphql_media_schema__Media);

export type MediaReadUserData = {
    userName: string;
};

export type MediaReadUserResponse = (MediaListCollection);

export type MediaSearchMediaData = {
    mediaType: string;
    searchQuery: string;
};

export type MediaSearchMediaResponse = (SearchPage);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);