/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutRelationsRouteImport } from './routes/_layout/relations'
import { Route as LayoutMissingRouteImport } from './routes/_layout/missing'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRelationsRoute = LayoutRelationsRouteImport.update({
  id: '/relations',
  path: '/relations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMissingRoute = LayoutMissingRouteImport.update({
  id: '/missing',
  path: '/missing',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/missing': typeof LayoutMissingRoute
  '/relations': typeof LayoutRelationsRoute
}
export interface FileRoutesByTo {
  '/missing': typeof LayoutMissingRoute
  '/relations': typeof LayoutRelationsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/missing': typeof LayoutMissingRoute
  '/_layout/relations': typeof LayoutRelationsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/missing' | '/relations'
  fileRoutesByTo: FileRoutesByTo
  to: '/missing' | '/relations' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/missing'
    | '/_layout/relations'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/relations': {
      id: '/_layout/relations'
      path: '/relations'
      fullPath: '/relations'
      preLoaderRoute: typeof LayoutRelationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/missing': {
      id: '/_layout/missing'
      path: '/missing'
      fullPath: '/missing'
      preLoaderRoute: typeof LayoutMissingRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutMissingRoute: typeof LayoutMissingRoute
  LayoutRelationsRoute: typeof LayoutRelationsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutMissingRoute: LayoutMissingRoute,
  LayoutRelationsRoute: LayoutRelationsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
